### ISSUE TITLE
Unable to reliably set value in Capacitor Gradle `variables.gradle` file

### ISSUE THREAD

**Issue by ZaLiTHkA** [ionic-team/trapeze#120]
I'm just getting to grips with Trapeze at the moment, so I do apologise if I'm missing something here..

I'm doing this in a freshly generated Ionic Angular project, using latest current Capacitor 4, which started out with the following `android/variables.gradle` file:

```gradle
ext {
    minSdkVersion = 22
    compileSdkVersion = 32
    targetSdkVersion = 32
    androidxActivityVersion = '1.4.0'
    androidxAppCompatVersion = '1.4.2'
    androidxCoordinatorLayoutVersion = '1.2.0'
    androidxCoreVersion = '1.8.0'
    androidxFragmentVersion = '1.4.1'
    coreSplashScreenVersion = '1.0.0-rc01'
    androidxWebkitVersion = '1.4.0'
    junitVersion = '4.13.2'
    androidxJunitVersion = '1.1.3'
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
}
```

all I'm trying to do is "update or insert" the following:

```gradle
ext {
    ...
    firebaseMessagingVersion = '20.0.6'
}
```

---

now in my Trapeze `yaml` file, when I use...

```yaml
platforms:
  android:
    gradle:
      - file: variables.gradle
        target:
          ext:
            firebaseMessagingVersion:
        replace:
          firebaseMessagingVersion: '20.0.6'
```

..I get the following output:

```gradle
ext {
    ...
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
    firebaseMessagingVersion 20.0.6
}
```

to be fair, I have tried many other things... most of which I'm too ashamed to share here (I got each letter of a string on it's own line.. **many** times).

anyway, my knowledge of YAML is very limited, so am I doing something silly here without realising it? or is this perhaps something that Trapeze doesn't currently handle..?

**Comment by mlynch** [comment]
There was some work I did to support this, and the test for it passes: https://github.com/ionic-team/trapeze/blob/main/packages/project/test/gradle-file.android.test.ts#L379

But perhaps when it's coming from the yaml/configuration tool something is making this break. I'll take look

**Comment by ZaLiTHkA** [comment]
thanks Max, appreciate that.. 👍🏼 

as far as I can tell, Trapeze doesn't care much about repo structure.... but FYI: this **is** inside a Nx Workspace. I execute this from root as a package script that calls `trapeze run apps/my-cool-app/trapeze.android.yaml --android-project apps/my-cool-app/android`.

and, unfortunately, since it probably does matter: I am on Windows. :/

**Comment by ZaLiTHkA** [comment]
> _edit_: I'll try the Trapeze Project API route as well actually, I've already got that set up in a script for bumping project versions along with `yarn version`.

after loading the project, the following snippet seems to give me the same result:

```js
const gradle = await project.android?.getGradleFile('variables.gradle');
// await gradle?.parse(); //! is this needed? it's from the tests..

await gradle?.replaceProperties(
  {
    ext: {
      firebaseMessagingVersion: {},
    },
  },
  { firebaseMessagingVersion: "'20.0.6'" },
);
```

although, _this_ way I managed to get it wrapped as a string, but still no `=`:

```gradle
{
    ...
    androidxEspressoCoreVersion = '3.4.0'
    cordovaAndroidVersion = '10.1.1'
    firebaseMessagingVersion '20.0.6'
}
```

**Comment by mlynch** [comment]
Okay thanks for trying that, taking a look now

**Comment by mlynch** [comment]
Okay I see it's because you're doing an insert rather than a replace. Did you try using `insert`? I'll take a look tomorrow

**Comment by ZaLiTHkA** [comment]
> Okay I see it's because you're doing an insert rather than a replace. Did you try using `insert`? I'll take a look tomorrow

I did, but only with the initial YAML config file executed with `trapeze run`, haven't tried with the Project API yet.

IIRC though, that simply added an additional entry every time I ran it.. let me double check that quickly, will get back to you shortly.

**Comment by ZaLiTHkA** [comment]
hmm.. not sure if I'm using this correctly, but the closest I've come to the desired outcome is with the following:

```yaml
platforms:
  android:
    gradle:
      - file: variables.gradle
        target:
          ext:
        insert:
          - firebaseMessagingVersion: 20.0.6
```

..which outputs the same as before:

```gradle
ext {
    ...
    cordovaAndroidVersion = '10.1.1'
    firebaseMessagingVersion = '20.0.6'
    firebaseMessagingVersion 20.0.6
}
```

then on subsequent runs, it adds the same line again:

```gradle
ext {
    ...
    cordovaAndroidVersion = '10.1.1'
    firebaseMessagingVersion = '20.0.6'
    firebaseMessagingVersion 20.0.6
    firebaseMessagingVersion 20.0.6
}
```

could you perhaps just confirm which syntax I **should** be using to achieve this..? if I knew both thet "correct" YAML config and scipted API logic is appropriate for this, I could test it more effectively.

sorry, serious YAML noob over here.. 🤓

**Comment by ZaLiTHkA** [comment]
just to note: I've just seen that the `packages/project/test/gradle-file.android.test.ts` file doesn't actually include any tests for an "insert" action with the structure found in `variables.gradle`.. it has two for "replace" though, starting on lines [379](https://github.com/ionic-team/trapeze/blob/1e8b2523f86c1206dbfecb50886ff9fcc2978822/packages/project/test/gradle-file.android.test.ts#L379) and [482](https://github.com/ionic-team/trapeze/blob/1e8b2523f86c1206dbfecb50886ff9fcc2978822/packages/project/test/gradle-file.android.test.ts#L482).

**Comment by mlynch** [comment]
Sorry I should have said that I don't think this was added when using insert and not inserting a string of raw gradle.

Don't worry about trying to make it work, I'll give you an official recommendation later today

**Comment by mlynch** [comment]
Also what I meant about insert was sending it raw source:

```yaml
      - file: app/build.gradle
        target:
        insert: |
          firebaseMessagingVersion = '20.0.6'
```

Example:

<img width="560" alt="image" src="https://user-images.githubusercontent.com/11214/201367812-4724c645-8d58-4e9d-8a12-7e5f72530ff6.png">

Working on adding a flag to the insert operation to support customizing the type of insert when using the object format

**Comment by mlynch** [comment]
Fixed in 6.0.0. here's how to use it:

```yaml
      - file: variables.gradle
        target:
          ext:
        insertType: 'variable'
        insert:
          - firebaseMessagingVersion: '20.0.6'
```

**Comment by ZaLiTHkA** [comment]
That looks awesome, nice and succinct. I'm not at my PC right now, but I'll most definitely play with this before I go to bed tonight.. 🤘 Thank you.

**Comment by ZaLiTHkA** [comment]
just cleaning up some open tabs here.. just wanted to drop a courtesy message here to say that a great deal has changed since I last visited this thread, and I'm not currently using `@trapezedev/configure`  in my workspace at the moment. hence the lack of feedback here.. (apologies)

I did still have issues trying to solve the "problem" from my original message here, but they were too intertwined with other things inside a Nx workspace, and I just needed to make it work.

with that said, I _am_ still using `@trapezedev/project` from custom workspace scripts, which is super helpful. 🖖🏼

**Comment by ngandon** [comment]
I struggled to make it work.

To be able to inject a string value, you must use the syntaxt :
```     
- file: variables.gradle
        target:
          ext:
        insertType: 'variable'
        insert:
          - firebaseMessagingVersion: "'23.0.5'"
```
to obtain inside variables.gradle :
```
    firebaseMessagingVersion = '23.0.5'
```
instead of
```
    firebaseMessagingVersion = 23.0.5
```

(version used 7.0.10)
